version: '3.8'

services:
  mcp-server:
    image: adalmia/rb_mcp:latest
    ports:
      - "8000:8000"
    container_name: mcp-server
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
