version: '3.8'

services:
  mcp-server:
    image: your-image-name:tag # Replace with your actual image name and tag
    ports:
      - "8000:8000"
    container_name: mcp-server
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
